### ISSUE TITLE
Plugin isn't working on realm 7.0

### ISSUE THREAD

**Issue by ikurek** [kamgurgul/Flipper-Realm#2]
After updating to realm 7.0, no data is displayed in Flipper. Will this plugin be updated to support Realm 7.0?

**Comment by kamgurgul** [comment]
I created new driver version which should support Realm 7+. Because Realm introduced breaking changes to the internal API I need to support two versions of the driver. It should work fine but I’m no longer working with Realm database so I didn’t test it correctly. If you encounter any issue please report it.

**Comment by afaucogney** [comment]
@ikurek @kamgurgul  it doesn't work here. Someone already succeed ?

**Comment by ikurek** [comment]
@afaucogney You're probably using a newer version of RealmDB

**Comment by kamgurgul** [comment]
> @ikurek @kamgurgul it doesn't work here. Someone already succeed ?

Are you using Realm 10? Probably it will require some changes inside drivers. I will take a look.

**Comment by afaucogney** [comment]
no realm 7.0.3. I running to downgrade to 6 to check if if works well. Will keep you updated

**Comment by afaucogney** [comment]
Sorry, it was my fault. The issue waas due to a miss configuration. I use a inMemory setup, and this was not compatible. A meesage about it apperas with realm 6.x, but not with 7.x. It does help me to figure out what was going wrong.

I will try with realm 10 soon, and let you know if it does work.
